### PR TITLE
[v2.1.2] Fixed migration blueprints macros conditioning

### PR DESCRIPTION
**Pull request by GoodM4ven**

### CODE REVIEW

**Comment by GoodM4ven** [comment]
* **#10** <a href="https://app.graphite.dev/github/pr/VPremiss/Arabicable/10?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @GoodM4ven and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Haaabeeel — CHANGES_REQUESTED** [review]
I think we should account for full-search indexing only when it's not a testing environment, maybe -OR... we could change sqlite to mysql for the tests, but I don't know!

**Comment by GoodM4ven** [comment]
Okay, can you at least take care of it; cause I'd quit! @Haaabeeel

**Comment by Haaabeeel** [comment]
I think we should do the same `app()->environment('testing')` checking thing. Because having a custom MySQL database for testing by each team is going to be tough, and I don't think we'd be testing Scout's full-text-search ability or something so... -I'm on it!

**Review by Haaabeeel — APPROVED** [review]

**Comment by Haaabeeel** [comment]
### Merge activity

* **Apr 21, 8:08 AM EDT**: @Haaabeeel started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/VPremiss/Arabicable/10).

**Pull request merged**
