### PR TITLE
[v2.1.2] Fixed migration blueprints macros conditioning

### PR DESCRIPTION
**Pull request by Haaabeeel**
Restricting the full-text-search index was necessary.

### CODE REVIEW

**Comment by Haaabeeel** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/VPremiss/Arabicable/11?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#11** <a href="https://app.graphite.dev/github/pr/VPremiss/Arabicable/11?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#10** <a href="https://app.graphite.dev/github/pr/VPremiss/Arabicable/10?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Haaabeeel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by GoodM4ven** [comment]
Yep.

**Review by GoodM4ven — APPROVED** [review]
Solid.

**Comment by Haaabeeel** [comment]
### Merge activity

* **Apr 21, 8:08 AM EDT**: @Haaabeeel started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/VPremiss/Arabicable/11).

**Pull request merged**
