### PR TITLE
[v3.0.0] Implement the config setup in Crafty

### PR DESCRIPTION
**Pull request by GoodM4ven**
Congrats, @Haaabeeel . Your package-config works! 𓁹‿𓁹

### CODE REVIEW

**Comment by GoodM4ven** [comment]
* **#15** <a href="https://app.graphite.dev/github/pr/VPremiss/Arabicable/15?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @GoodM4ven and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by GoodM4ven** [comment]
Hey, @Haaabeeel . Are we sure about this situation? We keep having to exclude the service provider from static analysis because of Unhandled match cases...

**Comment by Haaabeeel** [comment]
My bad, I'm such a banana! We have to do that, yes. But also something else that I cannot remember! Just give me few minutes! xD

**Comment by Haaabeeel** [comment]
Look at this structure here for checking indented configuration keys:

```php
try {
    $packageName = str($configKey)->before('.')->value();
    $mainKey = str($configKey)->after('.')->before('.')->value();

    $packageServiceProvider->configValidation("$packageName.$mainKey");
} catch (UnhandledMatchError) {
    throw new ConfiguratedValidatedConfigurationException(
        'The config key is not handled among configValidation() match cases.'
    );
}
```

That's what I've failed to take into account. And you're implementation is solid. Full keys to default values and only main keys for validations.

```php
public function configValidation(string $configKey): void
{
    $this->validations();
    match ($configKey) {
        'arabicable.property_suffix_keys' => $this->validatePropertySuffixKeysConfig(),
        'arabicable.spacing_after_punctuation_only' => $this->validateSpacingAfterPunctuationOnlyConfig(),
        'arabicable.normalized_punctuation_marks' => $this->validateNormalizedPunctuationMarksConfig(),
        'arabicable.space_preserved_enclosings' => $this->validateSpacePreservedEnclosingsConfig(),
        'arabicable.common_arabic_text' => $this->validateCommonArabicTextConfig(),
    };
}

public function configDefault(string $configKey): mixed
{
    return match ($configKey) {
        'arabicable.property_suffix_keys.numbers_to_indian' => '_indian',
        'arabicable.property_suffix_keys.text_with_harakat' => '_with_harakat',
        'arabicable.property_suffix_keys.text_for_search' => '_searchable',
        'arabicable.spacing_after_punctuation_only' => false,
        'arabicable.normalized_punctuation_marks' => [
            '«' => ['<', '<<'],
            '»' => ['>', '>>'],
        ],
        'arabicable.space_preserved_enclosings' => [
            '{', '}',
        ],
        'arabicable.common_arabic_text.model' => \VPremiss\Arabicable\Models\CommonArabicText::class,
        'arabicable.common_arabic_text.factory' => \VPremiss\Arabicable\Database\Factories\CommonArabicTextFactory::class,
    };
}
```

-Wait a second! This `$this->validations();` doesn't have to be here!

**Comment by GoodM4ven** [comment]
@Haaabeeel Dude, come on, why can't I upgrade via composer?

**Comment by Haaabeeel** [comment]
I just did make a release. -forgot to. sorry @GoodM4ven . Try it now

**Comment by GoodM4ven** [comment]
Finally, thanks. :+1:

**Comment by GoodM4ven** [comment]
HOLY GOD! Are you telling me that I should rewrite now?! @Haaabeeel
(╯°□°）╯︵ ┻━┻

**Comment by Haaabeeel** [comment]
sorry, but I don't need extra tables!

(╯°□°)╯︵ ┻━┻ ︵ ╯(°□° ╯)

**Comment by GoodM4ven** [comment]
No, seriously, this should have a breaking change: v3

**Comment by Haaabeeel** [comment]
v3.0.0 released

**Comment by GoodM4ven** [comment]
Ooof! Seems like hard-coding composer is so necessary for even dealing around fixing a freakin' facade doc-block method-hinting??!! Crazy tech we live in! (⊙_◎)"

**Pull request merged**
